### PR TITLE
Issue #211 In S1172 ignore methods that are passed to delegates ...

### PR DESCRIPTION
**Pull request by andwi**
…or event handlers

A project I work on has very large number of warnings due to this issue. So I thought this is a great time to start learning about Roslyn code analyzers and try to fix it myself.

I think I've got a solution that works. I have verified against a modified version of the existing MethodParameterUnused test. But the ItSources_Match_Expected_All test fails and I have no idea how to geet this test green. I would appreciate some help on this.

### CODE REVIEW

**Comment by tvsonar** [comment]
@andwi Thanks for the PR. To fix the ruling test, you need to update the corresponding expected file: https://github.com/SonarSource/sonarlint-vs/blob/master/src/Tests/SonarLint.RulingTest/Expected/S1172.json
When you run the `ItSources_Match_Expected_All` test, it generates the actual files in your `sonarlint-vs\src\Tests\SonarLint.RulingTest\bin\Debug\Actual\` folder. Here you'll find the S1172.json file which needs to be compared to the expected one. Check some/all of the differences to see if you only removed cases that you wanted. If that is the case, then overwrite the expected file and the test should be green.

**Comment by andwi** [comment]
@tvsonar Thanks for the explanation. I found some issues in the code by going over the expected file. Will soon update the PR.

**Comment by dbolkensteyn** [comment]
Any news on this @andwi ? It's been a while, I'm going to have to close this PR if the issue isn't resolved

**Comment by dbolkensteyn** [comment]
@tvsonar Is this something that, from a functional point of view, you'd like to do? If so, could you please create an issue?

**Pull request closed without merging**
