### PR TITLE
Enable SQ analysis on PR

### PR DESCRIPTION
**Pull request by dbolkensteyn**

### CODE REVIEW

**Comment by dbolkensteyn** [comment]
well well FxCop's execution is leading to the overall failure on MSBuild on SonarLint. VS ... independently of the SonarQube integration:

```
msbuild /p:RunCodeAnalysis=true
echo %errorlevel%
```

That's not exactly good news nor what I expected

**Comment by dbolkensteyn** [comment]
@tvsonar Can you have a look at why FxCop is failing?

**Comment by tvsonar** [comment]
@dbolkensteyn can you exclude the VISX project from SQ analysis? (as discussed we couldn't find any better short term solution)

**Comment by dbolkensteyn** [comment]
This solution isn't good enough - Dory is now available online and we should be able to use it.

**Pull request closed without merging**
